### ISSUE TITLE
why😭

### ISSUE THREAD

**Issue by ivythegreenest** [pikachub2005/replapi-it#2]
**Describe the bug**
tgis lbirbary carshes😡😡😡

**To Reproduce**
- put code below in a repl (index.js):
```js
const Client = require('replapi-it');
const client = new Client(process.env.SID);

client.on('ready', async () => {
	let user = await client.users.fetch('Seven7Four4');
	console.log(user.followerCount);
})
```
- put SID in secrets tab
- run the code

**Expected behavior**
get my floloewer cnout

**Screenshots**
![image](https://user-images.githubusercontent.com/117580169/208799867-da18f45c-24c8-459e-9f22-cf6731388004.png)

**Additional context**
do not

**Comment by 7heMech** [comment]
Should be fixed with the new update.
