### ISSUE TITLE
Why do you need an SID?

### ISSUE THREAD

**Issue by Tulip-0333** [pikachub2005/replapi-it#4]
When running this code, I simply commented out the line saying that "Uh oh spaghetti o your SID is invalid" and the code worked absolutely fine. I see absolutely no reason to have the line, or SIDs in the first place.

**Comment by sonicx180** [comment]
You need a sid for automations

**Comment by pikachub2005** [comment]
Many API requests require authentication

**Comment by gooddavvy** [comment]
@Tulip-0333 I'm a month late, but you can learn to get a SID [here](https://replit.com/talk/learn/How-to-Get-Your-SID-Cookie/145979). A SID cookie is required because... well I don't know but I know that Many API requests require authentication. SID is a cookie.
