### ISSUE TITLE
Feature Request: Recursedir

### ISSUE THREAD

**Issue by techpixel** [pikachub2005/replapi-it#7]
**Describe the solution you'd like**
Add a `recursedir` function like [crosis4furrets](https://github.com/rayhanadev/crosis4furrets/)

**Comment by pikachub2005** [comment]
I'll look into it for v3.2.0. I'm adding a *lot* of new stuff but it'll be out soon. =P

**Comment by pikachub2005** [comment]
Done! =P

**Comment by techpixel** [comment]
When will this be commited/merged?

**Comment by pikachub2005** [comment]
> When will this be committed/merged?

I'm rewriting most of it, but I've been working on it for a while and there's only a few things left. I'd say sometime next week, if not earlier?
